### ISSUE TITLE
Suggestion to Add a Github Topic

### ISSUE THREAD

**Issue by dylan-k** [troynt/elite_dangerous_controls_reference#1]
Github has a tags feature that I've found to be quite useful for finding [repos related to Elite Dangerous](https://github.com/topics/elite-dangerous). I noticed that this one might benefit from adding the `elite-dangerous` tag. Github calls them topics and says: To associate your repository with the elite-dangerous topic, visit your repo's landing page and select "manage topics."

This is a very useful tool for Elite Dangerous players, and I hope this would help it get out there to more of them. Thanks for making this!

**Comment by troynt** [comment]
Done! Thanks for suggestion.
